env_files:
  github_token: ~/.config/goreleaser/github_token
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/facce
    binary: facce
    ldflags: -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
archives:
  - format: zip
    replacements:
      amd64: x86_64
      386: x86
      darwin: macOS
